# networks
version: '2.0'

# networks
# create a network 'guacnetwork_compose' in mode 'bridged'
networks:
  guacnetwork_compose:
    driver: bridge

# services
services:
  # guacd
  guacd:
    container_name: guacd_compose
    image: ${IMAGE1}
    networks:
      guacnetwork_compose:
    restart: on-failure
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw
  # postgres
  postgres:
    container_name: postgres_guacamole_compose
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'systems1234'
      POSTGRES_USER: guacamole_user
    image: ${IMAGE2}
    networks:
      guacnetwork_compose:
    restart: on-failure
    volumes:
    - ./init:/docker-entrypoint-initdb.d:z
    - ./data:/var/lib/postgresql/data:Z

  # guacamole
  guacamole:
    container_name: guacamole_compose
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: 'systems1234'
      POSTGRES_USER: guacamole_user
    image: ${IMAGE3}
    links:
    - guacd
    networks:
      guacnetwork_compose:
   # ports:
   # - 8080/tcp
    restart: on-failure

  # nginx
  nginx:
   container_name: nginx_guacamole_compose
   restart: on-failure
   image: ${IMAGE4}
   volumes:
   - ./nginx/templates:/etc/nginx/templates:ro
   - ./nginx/ssl/self.cert:/etc/nginx/ssl/self.cert:ro
   - ./nginx/ssl/self-ssl.key:/etc/nginx/ssl/self-ssl.key:ro
   ports:
   - 8443:443
   links:
   - guacamole
   networks:
     guacnetwork_compose:
